### ISSUE TITLE
Require once failure

### ISSUE THREAD

**Issue by kngs** [elisseck/com.elisseck.discountreport#1]
Hi Eli,  Thanks for the Discount report extension!
I got a the following warning/failure when trying to install the report extension on a demo site of ours: "Warning: require_once(CRM/Discountreport/Form/Report/incomeDetailWithDiscounts.php): failed to open stream: No such file or directory in /home/greenleaf/www/civi45wp/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php on line 451". All paths look ok; Tried clearing caches and enable/disable Am I missing something?

**Comment by elisseck** [comment]
Hello! Sorry I packed this up and threw it onto github really hastily because it sounded like some folks wanted to see the SQL query involved... I see the issue (I originally mistyped the report class name without camelCase ... changed it in the report.php and report.tpl but NOT in report.php.mgd ... let me commit that change and you can pull it down again and let me know how that goes.

**Comment by elisseck** [comment]
@kngs Okay if you pull from master again (and possibly uninstall/reinstall the extension) I believe I fixed my typo. Keep in mind I really just intended this as a demo to collaborate with folks on better CiviDiscount reports and haven't tested it super thoroughly yet!

In fact... I'm going to add as much to the readme :)

**Comment by kngs** [comment]
Thanks! I'm in!! I will play around with it.  Let me know if I can help in any testing you want. - Karen

**Comment by elisseck** [comment]
I guess some useful feedback is if the stats actually "make sense" or if they're confusing :). I'm hoping one day to add a report that's more like the "Event Participant List" report but with a discount code column and filter, but i've been having trouble getting that one running properly.
